import Image from 'next/image'
import { SiteHeader } from '@/components/site-header'
import { getProducts } from '@/lib/shopify'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/JK%20Logo%20OK-AeCRffSQ2waJkiJgmYXrq3SDUIQWzD.png'
const hero = 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=2200&q=88'
const categories = [{ name: 'Metais', image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=85' }, { name: 'Banheiros', image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=900&q=85' }, { name: 'Cozinhas', image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=85' }, { name: 'Acessórios', image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=900&q=85' }]

export default async function Home() {
  const products = await getProducts(6)
  return <main id="top" className="overflow-hidden"><SiteHeader />
    <section className="relative flex min-h-[92vh] items-end px-5 pb-14 pt-36 md:px-10 md:pb-20"><Image src={hero} alt="Interior contemporâneo com metais e superfícies naturais" fill priority className="object-cover object-center" sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-t from-[#080b0f] via-[#080b0f]/30 to-[#080b0f]/15" /><div className="relative mx-auto w-full max-w-7xl"><p className="eyebrow mb-5">Metais · acabamentos · design · soluções</p><h1 className="display max-w-4xl text-6xl leading-[.87] text-white md:text-9xl">Detalhes que<br /><em className="text-[#c7b79b]">definem</em> espaços.</h1><div className="mt-10 flex flex-col gap-6 md:flex-row md:items-center md:justify-between"><p className="max-w-sm text-sm leading-6 text-white/65">Uma curadoria precisa para transformar matéria em presença. A JK SURFACES aproxima o design daquilo que você toca todos os dias.</p><a href="#colecao" className="w-fit border border-[#c7b79b] px-6 py-4 text-[10px] uppercase tracking-[.24em] text-[#c7b79b] transition-colors hover:bg-[#c7b79b] hover:text-[#080b0f]">Explorar a coleção</a></div></div></section>
    <section id="essencia" className="texture border-y border-white/10 px-5 py-28 md:px-10 md:py-40"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[.8fr_1.2fr] md:items-end"><p className="eyebrow">01 / Nossa essência</p><div><h2 className="display text-5xl leading-none text-white md:text-8xl">Qualidade.<br />Funcionalidade.<br /><span className="text-[#8ea0a6]">Design.</span></h2><p className="mt-10 max-w-md text-sm leading-7 text-white/55">O essencial bem resolvido. Selecionamos metais e acabamentos que equilibram performance, longevidade e a beleza silenciosa de uma escolha bem feita.</p></div></div></section>
    <section id="colecao" className="px-5 py-24 md:px-10 md:py-36"><div className="mx-auto max-w-7xl"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow mb-4">02 / A curadoria</p><h2 className="display text-5xl md:text-7xl">Explore superfícies</h2></div><span className="hidden text-[10px] uppercase tracking-[.2em] text-white/35 md:block">Arraste para descobrir</span></div><div className="flex snap-x gap-4 overflow-x-auto pb-4 md:grid md:grid-cols-4 md:overflow-visible">{categories.map((category) => <article key={category.name} className="group relative min-w-[74vw] snap-start md:min-w-0"><div className="relative aspect-[.78] overflow-hidden bg-[#11161b]"><Image src={category.image} alt={category.name} fill className="object-cover grayscale transition duration-700 group-hover:scale-105 group-hover:grayscale-0" sizes="(min-width: 768px) 25vw, 74vw" /><div className="absolute inset-0 bg-gradient-to-t from-[#080b0f]/80 to-transparent" /><h3 className="display absolute bottom-5 left-5 text-4xl text-white">{category.name}</h3></div></article>)}</div></div></section>
    <section className="bg-[#11161b] px-5 py-24 md:px-10 md:py-36"><div className="mx-auto max-w-7xl"><div className="mb-12 flex items-end justify-between"><div><p className="eyebrow mb-4">03 / Loja online</p><h2 className="display text-5xl md:text-7xl">Em destaque</h2></div><a href="#contato" className="hidden text-[10px] uppercase tracking-[.2em] text-[#c7b79b] md:block">Ver catálogo completo →</a></div>{products.length === 0 ? <div className="border border-white/10 p-10 text-sm leading-6 text-white/55">Nosso catálogo está sendo preparado. Fale com a equipe JK SURFACES para conhecer a curadoria disponível.</div> : <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <article key={product.id} className="group"><div className="relative aspect-square overflow-hidden bg-[#080b0f]">{product.featuredImage && <Image src={product.featuredImage.url} alt={product.featuredImage.altText || product.title} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width: 1024px) 33vw, 50vw" />}</div><div className="flex items-start justify-between gap-4 py-5"><div><h3 className="display text-3xl">{product.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-white/45">{product.description}</p></div><p className="whitespace-nowrap text-xs text-[#c7b79b]">{new Intl.NumberFormat('pt-BR', { style: 'currency', currency: product.priceRange.minVariantPrice.currencyCode }).format(Number(product.priceRange.minVariantPrice.amount))}</p></div></article>)}</div>}</div></section>
    <section className="px-5 py-28 md:px-10 md:py-40"><div className="mx-auto grid max-w-7xl gap-14 md:grid-cols-2 md:items-center"><div><p className="eyebrow mb-6">04 / Para seus projetos</p><h2 className="display text-6xl leading-[.9] md:text-8xl">O detalhe<br /><span className="text-[#c7b79b]">é a decisão.</span></h2></div><div className="border-l border-[#c7b79b] pl-7"><p className="text-lg leading-8 text-white/70">Da especificação à instalação, criamos soluções para quem não abre mão de fazer bem feito.</p><a href="mailto:contato@jksurfaces.com.br" className="mt-8 inline-block border-b border-[#c7b79b] pb-2 text-[10px] uppercase tracking-[.24em] text-[#c7b79b]">Fale com a JK SURFACES</a></div></div></section>
    <footer id="contato" className="border-t border-white/10 px-5 py-10 md:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-8 md:flex-row md:items-end md:justify-between"><div><Image src={logo} alt="JK Surfaces" width={180} height={70} className="h-12 w-auto object-contain object-left" /><p className="mt-5 text-xs text-white/40">Metais · acabamentos · design · soluções</p></div><div className="flex flex-col gap-3 text-right text-[10px] uppercase tracking-[.2em] text-white/50"><a href="https://www.instagram.com" className="hover:text-[#c7b79b]">Instagram</a><a href="https://wa.me/5500000000000" className="hover:text-[#c7b79b]">WhatsApp</a><span className="mt-4 text-white/25">© 2026 JK SURFACES</span></div></div></footer>
  </main>
}
